// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD09sEN6RMfK7SWh_BdKahgk6M1VjhfoXA',
    appId: '1:456366231776:web:34027535de4c950c6b4085',
    messagingSenderId: '456366231776',
    projectId: 'align-3ba4e',
    authDomain: 'align-3ba4e.firebaseapp.com',
    storageBucket: 'align-3ba4e.firebasestorage.app',
    measurementId: 'G-TGTCYL5KNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGaKkNFuIQCbrQnXekSPKvLI4hg75b6kw',
    appId: '1:456366231776:android:d637f89a1d07fa696b4085',
    messagingSenderId: '456366231776',
    projectId: 'align-3ba4e',
    storageBucket: 'align-3ba4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFn5k3BUmuEpLhCV9BgwGCKP-iLXJGU4g',
    appId: '1:456366231776:ios:70abdca64e317d386b4085',
    messagingSenderId: '456366231776',
    projectId: 'align-3ba4e',
    storageBucket: 'align-3ba4e.firebasestorage.app',
    iosBundleId: 'com.example.align',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFn5k3BUmuEpLhCV9BgwGCKP-iLXJGU4g',
    appId: '1:456366231776:ios:70abdca64e317d386b4085',
    messagingSenderId: '456366231776',
    projectId: 'align-3ba4e',
    storageBucket: 'align-3ba4e.firebasestorage.app',
    iosBundleId: 'com.example.align',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD09sEN6RMfK7SWh_BdKahgk6M1VjhfoXA',
    appId: '1:456366231776:web:6a98f96b2e7579776b4085',
    messagingSenderId: '456366231776',
    projectId: 'align-3ba4e',
    authDomain: 'align-3ba4e.firebaseapp.com',
    storageBucket: 'align-3ba4e.firebasestorage.app',
    measurementId: 'G-TRQE81B1P9',
  );
}
